//// Decompiled with JetBrains decompiler
//// Type: TaleWorlds.CampaignSystem.Party.PartyBase
//// Assembly: TaleWorlds.CampaignSystem, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
//// MVID: 21D5BF30-54A7-4DA5-81B3-31D796F5D6CE
//// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll

//using System;
//using System.Collections.Generic;
//using TaleWorlds.CampaignSystem.CharacterDevelopment;
//using TaleWorlds.CampaignSystem.ComponentInterfaces;
//using TaleWorlds.CampaignSystem.Extensions;
//using TaleWorlds.CampaignSystem.Map;
//using TaleWorlds.CampaignSystem.MapEvents;
//using TaleWorlds.CampaignSystem.Naval;
//using TaleWorlds.CampaignSystem.Roster;
//using TaleWorlds.CampaignSystem.Settlements;
//using TaleWorlds.CampaignSystem.Siege;
//using TaleWorlds.Core;
//using TaleWorlds.Library;
//using TaleWorlds.Localization;
//using TaleWorlds.SaveSystem;
//using TaleWorlds.SaveSystem.Load;

//#nullable disable
//namespace TaleWorlds.CampaignSystem.Party;

//public sealed class PartyBase : IBattleCombatant, IRandomOwner, IInteractablePoint
//{
//  [SaveableField(15)]
//  private int _remainingFoodPercentage;
//  [SaveableField(182)]
//  private CampaignTime _lastEatingTime = CampaignTime.Now;
//  [SaveableField(8)]
//  private Hero _customOwner;
//  [SaveableField(9)]
//  private int _index;
//  [SaveableField(200)]
//  private MapEventSide _mapEventSide;
//  [CachedData]
//  private int _partyMemberSizeLastCheckVersion;
//  [CachedData]
//  private int _cachedPartyMemberSizeLimit;
//  [CachedData]
//  private int _prisonerSizeLastCheckVersion;
//  [CachedData]
//  private int _cachedPrisonerSizeLimit;
//  [CachedData]
//  private int _lastNumberOfMenWithHorseVersionNo;
//  [CachedData]
//  private int _lastNumberOfMenPerTierVersionNo;
//  [SaveableField(17)]
//  private int _numberOfMenWithHorse;
//  private int[] _numberOfHealthyMenPerTier;
//  [CachedData]
//  private int _lastEstimatedStrengthVersionNo = -1;
//  [CachedData]
//  private float _cachedEstimatedStrength;
//  [SaveableField(20)]
//  private MBList<Ship> _ships = new MBList<Ship>();

//  internal static void AutoGeneratedStaticCollectObjectsPartyBase(
//    object o,
//    List<object> collectedObjects)
//  {
//    ((PartyBase) o).AutoGeneratedInstanceCollectObjects(collectedObjects);
//  }

//  private void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
//  {
//    CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime((object) this._lastEatingTime, collectedObjects);
//    collectedObjects.Add((object) this._customOwner);
//    collectedObjects.Add((object) this._mapEventSide);
//    collectedObjects.Add((object) this._ships);
//    collectedObjects.Add((object) this.Settlement);
//    collectedObjects.Add((object) this.MobileParty);
//    collectedObjects.Add((object) this.MemberRoster);
//    collectedObjects.Add((object) this.PrisonRoster);
//    collectedObjects.Add((object) this.ItemRoster);
//    collectedObjects.Add((object) this.CustomName);
//    collectedObjects.Add((object) this.CustomBanner);
//  }

//  internal static object AutoGeneratedGetMemberValueSettlement(object o)
//  {
//    return (object) ((PartyBase) o).Settlement;
//  }

//  internal static object AutoGeneratedGetMemberValueMobileParty(object o)
//  {
//    return (object) ((PartyBase) o).MobileParty;
//  }

//  internal static object AutoGeneratedGetMemberValueMemberRoster(object o)
//  {
//    return (object) ((PartyBase) o).MemberRoster;
//  }

//  internal static object AutoGeneratedGetMemberValuePrisonRoster(object o)
//  {
//    return (object) ((PartyBase) o).PrisonRoster;
//  }

//  internal static object AutoGeneratedGetMemberValueItemRoster(object o)
//  {
//    return (object) ((PartyBase) o).ItemRoster;
//  }

//  internal static object AutoGeneratedGetMemberValueRandomValue(object o)
//  {
//    return (object) ((PartyBase) o).RandomValue;
//  }

//  internal static object AutoGeneratedGetMemberValueCustomName(object o)
//  {
//    return (object) ((PartyBase) o).CustomName;
//  }

//  internal static object AutoGeneratedGetMemberValueCustomBanner(object o)
//  {
//    return (object) ((PartyBase) o).CustomBanner;
//  }

//  internal static object AutoGeneratedGetMemberValue_remainingFoodPercentage(object o)
//  {
//    return (object) ((PartyBase) o)._remainingFoodPercentage;
//  }

//  internal static object AutoGeneratedGetMemberValue_lastEatingTime(object o)
//  {
//    return (object) ((PartyBase) o)._lastEatingTime;
//  }

//  internal static object AutoGeneratedGetMemberValue_customOwner(object o)
//  {
//    return (object) ((PartyBase) o)._customOwner;
//  }

//  internal static object AutoGeneratedGetMemberValue_index(object o)
//  {
//    return (object) ((PartyBase) o)._index;
//  }

//  internal static object AutoGeneratedGetMemberValue_mapEventSide(object o)
//  {
//    return (object) ((PartyBase) o)._mapEventSide;
//  }

//  internal static object AutoGeneratedGetMemberValue_numberOfMenWithHorse(object o)
//  {
//    return (object) ((PartyBase) o)._numberOfMenWithHorse;
//  }

//  internal static object AutoGeneratedGetMemberValue_ships(object o)
//  {
//    return (object) ((PartyBase) o)._ships;
//  }

//  public CampaignVec2 Position
//  {
//    get => !this.IsMobile ? this.Settlement.Position : this.MobileParty.Position;
//  }

//  public bool IsVisible => !this.IsMobile ? this.Settlement.IsVisible : this.MobileParty.IsVisible;

//  public bool IsActive => !this.IsMobile ? this.Settlement.IsActive : this.MobileParty.IsActive;

//  public SiegeEvent SiegeEvent
//  {
//    get => !this.IsMobile ? this.Settlement.SiegeEvent : this.MobileParty.SiegeEvent;
//  }

//  public void OnVisibilityChanged(bool value)
//  {
//    this.MapEvent?.PartyVisibilityChanged(this, value);
//    CampaignEventDispatcher.Instance.OnPartyVisibilityChanged(this);
//    this.SetVisualAsDirty();
//  }

//  [SaveableProperty(1)]
//  public Settlement Settlement { get; private set; }

//  [SaveableProperty(2)]
//  public MobileParty MobileParty { get; private set; }

//  public bool IsSettlement => this.Settlement != null;

//  public bool IsMobile => this.MobileParty != null;

//  [SaveableProperty(3)]
//  public TroopRoster MemberRoster { get; private set; }

//  [SaveableProperty(4)]
//  public TroopRoster PrisonRoster { get; private set; }

//  [SaveableProperty(5)]
//  public ItemRoster ItemRoster { get; private set; }

//  public TextObject Name
//  {
//    get
//    {
//      if (this.IsSettlement)
//        return this.Settlement.Name;
//      return !this.IsMobile ? TextObject.GetEmpty() : this.MobileParty.Name;
//    }
//  }

//  public float DaysStarving => !this.IsStarving ? 0.0f : this._lastEatingTime.ElapsedDaysUntilNow;

//  public void OnConsumedFood() => this._lastEatingTime = CampaignTime.Now;

//  public int RemainingFoodPercentage
//  {
//    get => this._remainingFoodPercentage;
//    set => this._remainingFoodPercentage = value;
//  }

//  public bool IsStarving => this._remainingFoodPercentage < 0;

//  public string Id => this.MobileParty?.StringId ?? this.Settlement.StringId;

//  public float HealingRateForMemberRegulars
//  {
//    get
//    {
//      return Campaign.Current.Models.PartyHealingModel.GetDailyHealingForRegulars(this, false).ResultNumber;
//    }
//  }

//  public ExplainedNumber HealingRateForMemberRegularsExplained
//  {
//    get => Campaign.Current.Models.PartyHealingModel.GetDailyHealingForRegulars(this, false, true);
//  }

//  public float HealingRateForMemberHeroes
//  {
//    get
//    {
//      return Campaign.Current.Models.PartyHealingModel.GetDailyHealingHpForHeroes(this, false).ResultNumber;
//    }
//  }

//  public ExplainedNumber HealingRateForMemberHeroesExplained
//  {
//    get => Campaign.Current.Models.PartyHealingModel.GetDailyHealingHpForHeroes(this, false, true);
//  }

//  public Hero Owner
//  {
//    get
//    {
//      Hero customOwner = this._customOwner;
//      if (customOwner != null)
//        return customOwner;
//      return !this.IsMobile ? this.Settlement.Owner : this.MobileParty.Owner;
//    }
//  }

//  public void SetCustomOwner(Hero customOwner) => this._customOwner = customOwner;

//  public Hero LeaderHero => this.MobileParty?.LeaderHero;

//  public static PartyBase MainParty
//  {
//    get => Campaign.Current == null ? (PartyBase) null : Campaign.Current.MainParty.Party;
//  }

//  public static bool IsPartyUnderPlayerCommand(PartyBase party)
//  {
//    return Campaign.Current.Models.EncounterModel.IsPartyUnderPlayerCommand(party);
//  }

//  public bool LevelMaskIsDirty { get; private set; }

//  public void SetLevelMaskIsDirty() => this.LevelMaskIsDirty = true;

//  public void OnLevelMaskUpdated() => this.LevelMaskIsDirty = false;

//  public int Index
//  {
//    get => this._index;
//    private set => this._index = value;
//  }

//  public bool IsValid => this.Index >= 0;

//  public IFaction MapFaction
//  {
//    get
//    {
//      if (this.MobileParty != null)
//        return this.MobileParty.MapFaction;
//      return this.Settlement != null ? this.Settlement.MapFaction : (IFaction) null;
//    }
//  }

//  [SaveableProperty(210)]
//  public int RandomValue { get; private set; } = MBRandom.RandomInt(1, int.MaxValue);

//  public CultureObject Culture => this.MapFaction.Culture;

//  public Tuple<uint, uint> PrimaryColorPair
//  {
//    get
//    {
//      return this.MapFaction == null ? new Tuple<uint, uint>(4291609515U, 4291609515U) : new Tuple<uint, uint>(this.MapFaction.Color, this.MapFaction.Color2);
//    }
//  }

//  [SaveableProperty(216)]
//  public TextObject CustomName { get; private set; }

//  public void SetCustomName(TextObject name)
//  {
//    this.CustomName = name;
//    if (this.IsSettlement && !TextObject.IsNullOrEmpty(this.CustomName))
//      this.CustomName.SetSettlementProperties(this.Settlement);
//    this.SetVisualAsDirty();
//  }

//  [SaveableProperty(215)]
//  public Banner CustomBanner { get; private set; }

//  public void SetCustomBanner(Banner banner)
//  {
//    this.CustomBanner = banner;
//    this.SetVisualAsDirty();
//  }

//  public Banner Banner => !this.IsMobile ? this.Settlement.Banner : this.MobileParty.Banner;

//  int IBattleCombatant.GetTacticsSkillAmount()
//  {
//    return this.LeaderHero != null ? this.LeaderHero.GetSkillValue(DefaultSkills.Tactics) : 0;
//  }

//  public MapEvent MapEvent => this._mapEventSide?.MapEvent;

//  public MapEventSide MapEventSide
//  {
//    get => this._mapEventSide;
//    set
//    {
//      if (this._mapEventSide == value)
//        return;
//      if (value != null && this.IsMobile && this.MapEvent != null && this.MapEvent.DefenderSide.LeaderParty == this)
//        Debug.FailedAssert($"Double MapEvent For {this.Name}", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\PartyBase.cs", nameof (MapEventSide), (int) byte.MaxValue);
//      if (this._mapEventSide != null)
//        this._mapEventSide.RemovePartyInternal(this);
//      this._mapEventSide = value;
//      if (this._mapEventSide != null)
//        this._mapEventSide.AddPartyInternal(this);
//      if (this.MobileParty == null)
//        return;
//      if (this.IsActive)
//        this.MobileParty.CancelNavigationTransition();
//      foreach (MobileParty attachedParty in (List<MobileParty>) this.MobileParty.AttachedParties)
//        attachedParty.Party.MapEventSide = this._mapEventSide;
//    }
//  }

//  public BattleSideEnum Side
//  {
//    get
//    {
//      MapEventSide mapEventSide = this.MapEventSide;
//      return mapEventSide == null ? BattleSideEnum.None : mapEventSide.MissionSide;
//    }
//  }

//  public BattleSideEnum OpponentSide
//  {
//    get => this.Side == BattleSideEnum.Attacker ? BattleSideEnum.Defender : BattleSideEnum.Attacker;
//  }

//  CampaignVec2 IInteractablePoint.GetInteractionPosition(MobileParty interactingParty)
//  {
//    if (this.IsMobile)
//      return this.MobileParty.Position;
//    if (!this.IsSettlement)
//      return this.Position;
//    return !interactingParty.IsTargetingPort ? this.Settlement.GatePosition : this.Settlement.PortPosition;
//  }

//  bool IInteractablePoint.CanPartyInteract(MobileParty mobileParty, float dt)
//  {
//    bool flag = false;
//    if (this.IsMobile && (mobileParty.IsMainParty || !this.MobileParty.ShouldBeIgnored))
//      flag = mobileParty.IsCurrentlyAtSea == this.MobileParty.IsCurrentlyAtSea;
//    else if (this.IsSettlement)
//      flag = mobileParty.IsTargetingPort == mobileParty.IsCurrentlyAtSea && !mobileParty.IsTransitionInProgress;
//    if (flag)
//    {
//      CampaignVec2 targetPoint;
//      float neededMaximumDistanceForEncountering;
//      PartyBase.GetEncounterTargetPoint(dt, mobileParty, out targetPoint, out neededMaximumDistanceForEncountering);
//      float length = (mobileParty.Position - targetPoint).Length;
//      flag = mobileParty.BesiegedSettlement != null && mobileParty.BesiegedSettlement == mobileParty.TargetSettlement || (double) length < (double) neededMaximumDistanceForEncountering;
//    }
//    return flag;
//  }

//  void IInteractablePoint.OnPartyInteraction(MobileParty engagingParty)
//  {
//    if (this.IsMobile)
//    {
//      this.MobileParty.OnPartyInteraction(engagingParty);
//    }
//    else
//    {
//      if (!this.IsSettlement)
//        return;
//      this.Settlement.OnPartyInteraction(engagingParty);
//    }
//  }

//  private static void GetEncounterTargetPoint(
//    float dt,
//    MobileParty mobileParty,
//    out CampaignVec2 targetPoint,
//    out float neededMaximumDistanceForEncountering)
//  {
//    EncounterModel encounterModel = Campaign.Current.Models.EncounterModel;
//    neededMaximumDistanceForEncountering = mobileParty.Army == null ? MathF.Max(encounterModel.NeededMaximumDistanceForEncounteringMobileParty, dt * Campaign.Current.EstimatedMaximumLordPartySpeedExceptPlayer) : MathF.Clamp(encounterModel.NeededMaximumDistanceForEncounteringMobileParty * MathF.Sqrt((float) (mobileParty.Army.LeaderParty.AttachedParties.Count + 1)), MathF.Max(encounterModel.NeededMaximumDistanceForEncounteringMobileParty, dt * Campaign.Current.EstimatedMaximumLordPartySpeedExceptPlayer), MathF.Max(encounterModel.MaximumAllowedDistanceForEncounteringMobilePartyInArmy, dt * (Campaign.Current.EstimatedMaximumLordPartySpeedExceptPlayer + 0.01f)));
//    if (mobileParty.IsCurrentlyEngagingSettlement)
//    {
//      targetPoint = mobileParty.IsTargetingPort ? mobileParty.ShortTermTargetSettlement.PortPosition : mobileParty.ShortTermTargetSettlement.GatePosition;
//      neededMaximumDistanceForEncountering = mobileParty.ShortTermTargetSettlement.IsTown ? encounterModel.NeededMaximumDistanceForEncounteringTown : encounterModel.NeededMaximumDistanceForEncounteringVillage;
//      if (!mobileParty.IsTargetingPort)
//        return;
//      SiegeEvent siegeEvent = mobileParty.ShortTermTargetSettlement.SiegeEvent;
//      if ((siegeEvent != null ? (siegeEvent.IsBlockadeActive ? 1 : 0) : 0) == 0)
//        return;
//      neededMaximumDistanceForEncountering = encounterModel.NeededMaximumDistanceForEncounteringBlockade;
//    }
//    else if (mobileParty.Army != null && mobileParty.Army.LeaderParty != mobileParty && mobileParty.ShortTermTargetParty.MapEvent != null && mobileParty.ShortTermTargetParty.MapEvent == mobileParty.Army.LeaderParty.MapEvent && mobileParty.Army.LeaderParty.AttachedParties.Contains(mobileParty))
//      targetPoint = mobileParty.Position;
//    else if (mobileParty.CurrentSettlement != null && mobileParty.ShortTermTargetParty.BesiegedSettlement == mobileParty.CurrentSettlement)
//      targetPoint = mobileParty.CurrentSettlement.GatePosition;
//    else
//      targetPoint = mobileParty.Ai.AiBehaviorInteractable.GetInteractionPosition(mobileParty);
//  }

//  internal void AfterLoad()
//  {
//    if (this.RandomValue == 0)
//      this.RandomValue = MBRandom.RandomInt(1, int.MaxValue);
//    TroopRoster prisonRoster = this.PrisonRoster;
//    if ((prisonRoster != null ? (prisonRoster.Contains(CharacterObject.PlayerCharacter) ? 1 : 0) : 0) != 0 && (this != Hero.MainHero.PartyBelongedToAsPrisoner || Hero.MainHero.PartyBelongedTo != null && Hero.MainHero.PartyBelongedToAsPrisoner != null))
//    {
//      if (Hero.MainHero.PartyBelongedTo == PartyBase.MainParty?.MobileParty)
//        this.PrisonRoster.AddToCounts(CharacterObject.PlayerCharacter, -1);
//      else
//        PlayerCaptivity.CaptorParty = this;
//    }
//    if (this.IsMobile && this.MobileParty.IsCaravan && !this.MobileParty.IsCurrentlyUsedByAQuest && this._customOwner != null && this.MobileParty.Owner != this.Owner)
//      this.SetCustomOwner((Hero) null);
//    foreach (TroopRosterElement troopRosterElement in (List<TroopRosterElement>) this.PrisonRoster.GetTroopRoster())
//    {
//      if (troopRosterElement.Character.HeroObject != null && troopRosterElement.Character.HeroObject.PartyBelongedToAsPrisoner == null)
//        this.PrisonRoster.RemoveTroop(troopRosterElement.Character);
//    }
//    if (!MBSaveLoad.IsUpdatingGameVersion || !(MBSaveLoad.LastLoadedGameVersion < ApplicationVersion.FromString("v1.2.0")))
//      return;
//    this.MemberRoster.RemoveZeroCounts();
//  }

//  internal void InitCache()
//  {
//    this._partyMemberSizeLastCheckVersion = -1;
//    this._prisonerSizeLastCheckVersion = -1;
//    this._lastNumberOfMenWithHorseVersionNo = -1;
//    this._lastNumberOfMenPerTierVersionNo = -1;
//    this._lastEstimatedStrengthVersionNo = -1;
//  }

//  [LoadInitializationCallback]
//  private void OnLoad(MetaData metaData, ObjectLoadData objectLoadData)
//  {
//    if (MBSaveLoad.LastLoadedGameVersion.IsOlderThan(ApplicationVersion.FromString("v1.3.0")))
//      this._ships = new MBList<Ship>();
//    this.InitCache();
//  }

//  public int PartySizeLimit
//  {
//    get
//    {
//      int versionNo = this.MemberRoster.VersionNo;
//      if (this._partyMemberSizeLastCheckVersion != versionNo || this._cachedPartyMemberSizeLimit == 0)
//      {
//        this._partyMemberSizeLastCheckVersion = versionNo;
//        this._cachedPartyMemberSizeLimit = (int) Campaign.Current.Models.PartySizeLimitModel.GetPartyMemberSizeLimit(this).ResultNumber;
//      }
//      return this._cachedPartyMemberSizeLimit;
//    }
//  }

//  public int PrisonerSizeLimit
//  {
//    get
//    {
//      int versionNo = this.PrisonRoster.VersionNo;
//      if (this._prisonerSizeLastCheckVersion != versionNo || this._cachedPrisonerSizeLimit == 0)
//      {
//        this._prisonerSizeLastCheckVersion = versionNo;
//        this._cachedPrisonerSizeLimit = (int) Campaign.Current.Models.PartySizeLimitModel.GetPartyPrisonerSizeLimit(this).ResultNumber;
//      }
//      return this._cachedPrisonerSizeLimit;
//    }
//  }

//  public ExplainedNumber PartySizeLimitExplainer
//  {
//    get => Campaign.Current.Models.PartySizeLimitModel.GetPartyMemberSizeLimit(this, true);
//  }

//  public ExplainedNumber PrisonerSizeLimitExplainer
//  {
//    get => Campaign.Current.Models.PartySizeLimitModel.GetPartyPrisonerSizeLimit(this, true);
//  }

//  public int NumberOfHealthyMembers
//  {
//    get => this.MemberRoster.TotalManCount - this.MemberRoster.TotalWounded;
//  }

//  public int NumberOfRegularMembers => this.MemberRoster.TotalRegulars;

//  public int NumberOfWoundedTotalMembers => this.MemberRoster.TotalWounded;

//  public int NumberOfAllMembers => this.MemberRoster.TotalManCount;

//  public int NumberOfPrisoners => this.PrisonRoster.TotalManCount;

//  public int NumberOfMounts => this.ItemRoster.NumberOfMounts;

//  public int NumberOfPackAnimals => this.ItemRoster.NumberOfPackAnimals;

//  public IEnumerable<CharacterObject> PrisonerHeroes
//  {
//    get
//    {
//      for (int j = 0; j < this.PrisonRoster.Count; ++j)
//      {
//        if (this.PrisonRoster.GetElementNumber(j) > 0)
//        {
//          TroopRosterElement elementCopyAtIndex = this.PrisonRoster.GetElementCopyAtIndex(j);
//          if (elementCopyAtIndex.Character.IsHero)
//            yield return elementCopyAtIndex.Character;
//        }
//      }
//    }
//  }

//  public int NumberOfMenWithHorse
//  {
//    get
//    {
//      if (this._lastNumberOfMenWithHorseVersionNo != this.MemberRoster.VersionNo)
//      {
//        this.RecalculateNumberOfMenWithHorses();
//        this._lastNumberOfMenWithHorseVersionNo = this.MemberRoster.VersionNo;
//      }
//      return this._numberOfMenWithHorse;
//    }
//  }

//  public int NumberOfMenWithoutHorse => this.NumberOfAllMembers - this.NumberOfMenWithHorse;

//  public int GetNumberOfHealthyMenOfTier(int tier)
//  {
//    if (tier < 0)
//    {
//      Debug.FailedAssert("Requested men count for negative tier.", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\Party\\PartyBase.cs", nameof (GetNumberOfHealthyMenOfTier), 587);
//      return 0;
//    }
//    bool flag = false;
//    if (this._numberOfHealthyMenPerTier == null || tier >= this._numberOfHealthyMenPerTier.Length)
//    {
//      this._numberOfHealthyMenPerTier = new int[MathF.Max(tier, 6) + 1];
//      flag = true;
//    }
//    else if (this._lastNumberOfMenPerTierVersionNo != this.MemberRoster.VersionNo)
//      flag = true;
//    if (flag)
//    {
//      for (int index = 0; index < this._numberOfHealthyMenPerTier.Length; ++index)
//        this._numberOfHealthyMenPerTier[index] = 0;
//      for (int index = 0; index < this.MemberRoster.Count; ++index)
//      {
//        CharacterObject characterAtIndex = this.MemberRoster.GetCharacterAtIndex(index);
//        if (characterAtIndex != null && !characterAtIndex.IsHero)
//        {
//          int tier1 = characterAtIndex.Tier;
//          if (tier1 >= 0 && tier1 < this._numberOfHealthyMenPerTier.Length)
//          {
//            int num = this.MemberRoster.GetElementNumber(index) - this.MemberRoster.GetElementWoundedNumber(index);
//            this._numberOfHealthyMenPerTier[tier1] += num;
//          }
//        }
//      }
//      this._lastNumberOfMenPerTierVersionNo = this.MemberRoster.VersionNo;
//    }
//    return this._numberOfHealthyMenPerTier[tier];
//  }

//  public float EstimatedStrength
//  {
//    get
//    {
//      if (this._lastEstimatedStrengthVersionNo == this.GetStrengthVersionNo())
//        return this._cachedEstimatedStrength;
//      this.UpdateEstimatedStrengthCaches();
//      return this._cachedEstimatedStrength;
//    }
//  }

//  private int GetStrengthVersionNo()
//  {
//    int num = this.MemberRoster.VersionNo;
//    if (this.IsMobile && this.MobileParty.IsCurrentlyAtSea)
//      num = this.GetShipsVersion() + num * 13;
//    int strengthVersionNo = num << 1;
//    if (this.MapEvent != null)
//      strengthVersionNo += this.Side == BattleSideEnum.Attacker ? 1 : 0;
//    return strengthVersionNo;
//  }

//  private void UpdateEstimatedStrengthCaches()
//  {
//    this._cachedEstimatedStrength = this.CalculateEstimatedCurrentStrength();
//    this._lastEstimatedStrengthVersionNo = this.GetStrengthVersionNo();
//  }

//  public float CalculateCurrentStrength()
//  {
//    float currentStrength = 0.0f;
//    if (this.IsMobile)
//    {
//      BattleSideEnum side = BattleSideEnum.Defender;
//      CampaignVec2 position = this.Position;
//      if (this.SiegeEvent != null && this.SiegeEvent.IsBlockadeActive && this.MapEvent != null && this.MapEvent.IsNavalMapEvent)
//        position = this.SiegeEvent.BesiegedSettlement.PortPosition;
//      MapEvent.PowerCalculationContext contextForPosition = Campaign.Current.Models.MilitaryPowerModel.GetContextForPosition(position);
//      if (this.MapEvent != null)
//        side = this.Side;
//      currentStrength = Campaign.Current.Models.MilitaryPowerModel.GetPowerOfParty(this, side, contextForPosition);
//    }
//    return currentStrength;
//  }

//  private float CalculateEstimatedCurrentStrength()
//  {
//    float estimatedCurrentStrength = 0.0f;
//    if (this.IsMobile)
//    {
//      BattleSideEnum side = BattleSideEnum.Defender;
//      if (this.MapEvent != null)
//        side = this.Side;
//      estimatedCurrentStrength = Campaign.Current.Models.MilitaryPowerModel.GetPowerOfParty(this, side, MapEvent.PowerCalculationContext.Estimated);
//    }
//    return estimatedCurrentStrength;
//  }

//  public float GetCustomStrength(BattleSideEnum side, MapEvent.PowerCalculationContext context)
//  {
//    return Campaign.Current.Models.MilitaryPowerModel.GetPowerOfParty(this, side, context);
//  }

//  public PartyBase(MobileParty mobileParty)
//    : this(mobileParty, (Settlement) null)
//  {
//  }

//  public PartyBase(Settlement settlement)
//    : this((MobileParty) null, settlement)
//  {
//  }

//  private PartyBase(MobileParty mobileParty, Settlement settlement)
//  {
//    this.Index = Campaign.Current.GeneratePartyId(this);
//    this.MobileParty = mobileParty;
//    this.Settlement = settlement;
//    this.ItemRoster = new ItemRoster();
//    this.MemberRoster = new TroopRoster(this);
//    this.PrisonRoster = new TroopRoster(this);
//  }

//  public MBReadOnlyList<Ship> Ships => (MBReadOnlyList<Ship>) this._ships;

//  public Ship FlagShip => this.Ships.MaxBy<Ship, float>((Func<Ship, float>) (x => x.FlagshipScore));

//  internal void AddShipInternal(Ship ship) => this._ships.Add(ship);

//  internal void RemoveShipInternal(Ship ship) => this._ships.Remove(ship);

//  public int GetShipsVersion()
//  {
//    int num = this.Ships.Count;
//    foreach (Ship ship in (List<Ship>) this.Ships)
//    {
//      uint versionNo = ship.VersionNo;
//      num = (int) (((long) (num * 31 /*0x1F*/) + (long) (versionNo << 5 | versionNo >> 3)) % 1000000007L);
//    }
//    return (num + this.Ships.Count * 31 /*0x1F*/) % 1000000007;
//  }

//  private void RecalculateNumberOfMenWithHorses()
//  {
//    this._numberOfMenWithHorse = 0;
//    for (int index = 0; index < this.MemberRoster.Count; ++index)
//    {
//      TroopRosterElement elementCopyAtIndex = this.MemberRoster.GetElementCopyAtIndex(index);
//      if (elementCopyAtIndex.Character != null && elementCopyAtIndex.Character.IsMounted)
//        this._numberOfMenWithHorse += elementCopyAtIndex.Number;
//    }
//  }

//  public int GetNumberOfMenWith(TraitObject trait)
//  {
//    int numberOfMenWith = 0;
//    foreach (TroopRosterElement troopRosterElement in (List<TroopRosterElement>) this.MemberRoster.GetTroopRoster())
//    {
//      if (troopRosterElement.Character.GetTraitLevel(trait) > 0)
//        numberOfMenWith += troopRosterElement.Number;
//    }
//    return numberOfMenWith;
//  }

//  public int AddPrisoner(CharacterObject element, int numberToAdd)
//  {
//    return this.PrisonRoster.AddToCounts(element, numberToAdd);
//  }

//  public int AddMember(CharacterObject element, int numberToAdd, int numberToAddWounded = 0)
//  {
//    return this.MemberRoster.AddToCounts(element, numberToAdd, woundedCount: numberToAddWounded);
//  }

//  public void AddPrisoners(TroopRoster roster)
//  {
//    foreach (TroopRosterElement troopRosterElement in (List<TroopRosterElement>) roster.GetTroopRoster())
//      this.AddPrisoner(troopRosterElement.Character, troopRosterElement.Number);
//  }

//  public void AddMembers(TroopRoster roster) => this.MemberRoster.Add(roster);

//  public override string ToString()
//  {
//    return !this.IsSettlement ? this.MobileParty.Name.ToString() : this.Settlement.Name.ToString();
//  }

//  public int AddElementToMemberRoster(CharacterObject element, int numberToAdd, bool insertAtFront = false)
//  {
//    return this.MemberRoster.AddToCounts(element, numberToAdd, insertAtFront);
//  }

//  public void AddToMemberRosterElementAtIndex(int index, int numberToAdd, int woundedCount = 0)
//  {
//    this.MemberRoster.AddToCountsAtIndex(index, numberToAdd, woundedCount);
//  }

//  public void WoundMemberRosterElements(CharacterObject elementObj, int numberToWound)
//  {
//    this.MemberRoster.AddToCounts(elementObj, 0, woundedCount: numberToWound);
//  }

//  public void WoundMemberRosterElementsWithIndex(int elementIndex, int numberToWound)
//  {
//    this.MemberRoster.AddToCountsAtIndex(elementIndex, 0, numberToWound);
//  }

//  public void UpdateVisibilityAndInspected(CampaignVec2 fromPosition, float mainPartySeeingRange = 0.0f)
//  {
//    bool isVisible = false;
//    bool isInspected = false;
//    if (this.IsSettlement)
//    {
//      isVisible = true;
//      if (this.Settlement.SettlementComponent is ISpottable settlementComponent && !settlementComponent.IsSpotted)
//        isVisible = false;
//      if (isVisible)
//        isInspected = PartyBase.CalculateSettlementInspected(fromPosition.ToVec2(), (IMapPoint) this.Settlement, mainPartySeeingRange);
//    }
//    else if (this.MobileParty.IsActive)
//    {
//      if (Campaign.Current.TrueSight)
//      {
//        isVisible = true;
//        isInspected = true;
//      }
//      else if (this.MobileParty.CurrentSettlement == null || this.MobileParty.LeaderHero?.ClanBanner != null || this.MobileParty.MapEvent != null && this.MobileParty.MapEvent.IsSiegeAssault && this.MobileParty.Party.Side == BattleSideEnum.Attacker)
//        PartyBase.CalculateVisibilityAndInspected(fromPosition.ToVec2(), (IMapPoint) this.MobileParty, out isVisible, out isInspected, mainPartySeeingRange);
//    }
//    if (this.IsSettlement)
//    {
//      this.Settlement.IsVisible = isVisible;
//      this.Settlement.IsInspected = isInspected;
//    }
//    else
//    {
//      this.MobileParty.IsVisible = isVisible;
//      this.MobileParty.IsInspected = isInspected;
//    }
//  }

//  private static void CalculateVisibilityAndInspected(
//    Vec2 fromPosition,
//    IMapPoint mapPoint,
//    out bool isVisible,
//    out bool isInspected,
//    float mainPartySeeingRange = 0.0f)
//  {
//    isInspected = false;
//    if ((mapPoint is MobileParty mobileParty ? mobileParty.Army : (Army) null) != null && mobileParty.Army.LeaderParty.AttachedParties.IndexOf(mobileParty) >= 0)
//      isVisible = mobileParty.Army.LeaderParty.IsVisible;
//    else if (mobileParty != null && mobileParty.SiegeEvent != null && mobileParty.SiegeEvent.BesiegedSettlement.IsInspected)
//    {
//      isVisible = true;
//    }
//    else
//    {
//      float visibilityRangeOfMapPoint = PartyBase.CalculateVisibilityRangeOfMapPoint(fromPosition, mapPoint, mainPartySeeingRange);
//      isVisible = (double) visibilityRangeOfMapPoint > 1.0 && mapPoint.IsActive;
//      if (!isVisible)
//        return;
//      if (mapPoint.IsInspected)
//        isInspected = true;
//      else
//        isInspected = 1.0 / (double) visibilityRangeOfMapPoint < (double) Campaign.Current.Models.MapVisibilityModel.GetPartyRelativeInspectionRange(mapPoint);
//    }
//  }

//  private static bool CalculateSettlementInspected(
//    Vec2 fromPosition,
//    IMapPoint mapPoint,
//    float mainPartySeeingRange = 0.0f)
//  {
//    return 1.0 / (double) PartyBase.CalculateVisibilityRangeOfMapPoint(fromPosition, mapPoint, mainPartySeeingRange) < (double) Campaign.Current.Models.MapVisibilityModel.GetPartyRelativeInspectionRange(mapPoint);
//  }

//  private static float CalculateVisibilityRangeOfMapPoint(
//    Vec2 fromPosition,
//    IMapPoint mapPoint,
//    float mainPartySeeingRange)
//  {
//    MobileParty mainParty = MobileParty.MainParty;
//    float lengthSquared = (fromPosition - mapPoint.Position.ToVec2()).LengthSquared;
//    float num1 = mainPartySeeingRange;
//    if ((double) mainPartySeeingRange == 0.0)
//      num1 = mainParty.SeeingRange;
//    double num2 = (double) num1 * (double) num1 / (double) lengthSquared;
//    float num3 = 0.25f;
//    if (mapPoint is MobileParty party)
//      num3 = Campaign.Current.Models.MapVisibilityModel.GetPartySpottingDifficulty(mainParty, party);
//    double num4 = (double) num3;
//    return (float) (num2 / num4);
//  }

//  public BasicCultureObject BasicCulture => (BasicCultureObject) this.Culture;

//  public BasicCharacterObject General
//  {
//    get
//    {
//      if (this.MobileParty?.Army != null)
//      {
//        MobileParty leaderParty = this.MobileParty.Army.LeaderParty;
//        if (leaderParty == null)
//          return (BasicCharacterObject) null;
//        Hero leaderHero = leaderParty.LeaderHero;
//        return leaderHero == null ? (BasicCharacterObject) null : (BasicCharacterObject) leaderHero.CharacterObject;
//      }
//      Hero leaderHero1 = this.LeaderHero;
//      return leaderHero1 == null ? (BasicCharacterObject) null : (BasicCharacterObject) leaderHero1.CharacterObject;
//    }
//  }

//  public void SetAsCameraFollowParty() => Campaign.Current.CameraFollowParty = this;

//  internal void OnFinishLoadState()
//  {
//    this.SetVisualAsDirty();
//    this.MobileParty?.OnFinishLoadState();
//  }

//  [CachedData]
//  public bool IsVisualDirty { get; private set; }

//  public void SetVisualAsDirty()
//  {
//    if (this.MobileParty != null)
//    {
//      if (!this.MobileParty.IsCurrentlyAtSea || this.MobileParty.IsTransitionInProgress)
//      {
//        SiegeEvent siegeEvent = this.MobileParty.SiegeEvent;
//        if ((siegeEvent != null ? (siegeEvent.IsBlockadeActive ? 1 : 0) : 0) == 0)
//          goto label_4;
//      }
//      this.MobileParty.SetNavalVisualAsDirty();
//    }
//label_4:
//    this.IsVisualDirty = true;
//  }

//  public void OnVisualsUpdated() => this.IsVisualDirty = false;

//  internal void OnHeroAdded(Hero heroObject, TroopRoster roster)
//  {
//    if (object.Equals((object) roster, (object) this.PrisonRoster))
//      heroObject.OnAddedToPartyAsPrisoner(this);
//    else
//      this.MobileParty?.OnHeroAdded(heroObject);
//  }

//  internal void OnHeroRemoved(Hero heroObject, TroopRoster roster)
//  {
//    if (object.Equals((object) roster, (object) this.PrisonRoster))
//      heroObject.OnRemovedFromPartyAsPrisoner(this);
//    else
//      this.MobileParty?.OnHeroRemoved(heroObject);
//  }

//  internal void OnXpChanged(TroopRoster roster, ref TroopRosterElement element)
//  {
//    CharacterObject character = element.Character;
//    if (!character.IsHero)
//    {
//      if (object.Equals((object) roster, (object) this.PrisonRoster))
//      {
//        int maxValue = element.Number * character.ConformityNeededToRecruitPrisoner;
//        int xp = element.Xp;
//        element.Xp = MBMath.ClampInt(xp, 0, maxValue);
//      }
//      else
//      {
//        int num1 = 0;
//        for (int index = 0; index < character.UpgradeTargets.Length; ++index)
//        {
//          int upgradeXpCost = character.GetUpgradeXpCost(this, index);
//          if (num1 < upgradeXpCost)
//            num1 = upgradeXpCost;
//        }
//        int num2 = MBMath.ClampInt(element.Xp, 0, element.Number * num1);
//        element.Xp = num2;
//      }
//    }
//    else
//      element.Xp = MathF.Max(element.Xp, 0);
//  }

//  internal void OnRosterSizeChanged(TroopRoster roster)
//  {
//    if (!object.Equals((object) roster, (object) this.MemberRoster))
//      return;
//    CampaignEventDispatcher.Instance.OnPartySizeChanged(this);
//  }
//}
